image: docker

stages:
  - build
  - deploy


build:
  stage: build

  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^release/'
      when: never
    - if: $CI_COMMIT_BRANCH
      when: manual
  
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA" .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"

  environment:
    name: build
    url: http://git.aispring.cloud
    action: stop

build_version:
  stage: build

  rules:
    - if: $CI_COMMIT_TAG      
    - if: '$CI_COMMIT_BRANCH !~ /^release/'
      when: never
    - if: $CI_COMMIT_BRANCH

   
  script:
    - echo ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  environment:
    name: build_version
    url: http://git.aispring.cloud
    on_stop: stop_review


deploy:
  stage: deploy

  only:
    - tags
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}

  environment:
    name: deploy
    url: http://git.aispring.cloud
