image: docker

stages:
  - build
  - deploy


build:
  stage: build
  script:
    - echo "$CI_REGISTRY_IMAGE:latest"
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .

build_version:
  stage: build
  only:
    - /^release\/.+$/
    - tag
  script:
    - echo ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} .


deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY    
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}